#!/bin/bash

# NOTE: block size should always be higher than rate_kHz
TEST_DURATION=5
i=0
for BLOCK_SIZE in 4 8 16 32 64 128 256 512
do
	for RATE_kHz in 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000
	do
		i=$(( i+1 ))
		sudo ./host $RATE_kHz $BLOCK_SIZE $TEST_DURATION
	done
	sleep 1s
done